name: Déploiement en continu

on:
    push:
      tags:
      - 'TP3-V*'

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore Seismoscope.sln
      - run: dotnet build Seismoscope.sln --no-restore --configuration Release
      - run: dotnet test SeismoscopeTest\SeismoscopeTest.csproj --verbosity normal

  publish:
    runs-on: windows-latest
    needs: test #Revalide que les tests passent pour déployer

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Créer App.config depuis secret
      run: |
        cat <<EOF > Seismoscope/App.config 
        ${{ secrets.APP_CONFIG_PROD }}
        EOF
      shell: bash
    
    - name: Publish WPF app
      run: >
        dotnet publish Seismoscope/Seismoscope.csproj
        --configuration Release
        --runtime win-x64
        --self-contained true
        --output publish

    - name: Generate installer with Inno Setup
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
      with:
        path: installer/setup.iss

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        draft: false
        files: installer/setup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
